import type { OLLDefinition } from "@/types/cube/333";
import { OLLCategory } from "@/enums/cube/333";

export type { OLLDefinition, OLLCaseId } from "@/types/cube/333";

export const definitions: OLLDefinition[] = [
  {
    id: "1",
    name: "1",
    setupAlgorithms: "F R' F' R U2' F R' F' R2' U2' R'",
    pattern: [
      "CC",
      "S-TC",
      "S-LT",
      "S-LC",
      "S-LB",
      "S-BC",
      "S-RT",
      "S-RC",
      "S-RB",
    ],
    algorithms: ["R U2 R2 F R F' U2 R' F R F'"],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "2",
    name: "2",
    setupAlgorithms: "f U R U' R' f' F U R U' R' F'",
    pattern: [
      "CC",
      "S-TC",
      "S-TR",
      "S-LT",
      "S-LC",
      "S-LB",
      "S-BC",
      "S-BR",
      "S-RC",
    ],
    algorithms: ["F R U R' U' F' f R U R' U' f'"],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "3",
    name: "3",
    setupAlgorithms: "F U R U' R' F' U f U R U' R' f' y",
    pattern: [
      "CC",
      "BL",
      "S-TL",
      "S-TC",
      "S-LC",
      "S-BC",
      "S-BR",
      "S-RT",
      "S-RC",
    ],
    algorithms: ["y' f R U R' U' f' U' F R U R' U' F'"],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "4",
    name: "4",
    setupAlgorithms: "F U R U' R' F' U' f U R U' R' f' y",
    pattern: [
      "CC",
      "BR",
      "S-TC",
      "S-TR",
      "S-LT",
      "S-LC",
      "S-BL",
      "S-BC",
      "S-RC",
    ],
    algorithms: ["y F' L' U' L U F U' f R U R' U' f'"],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "5",
    name: "5",
    setupAlgorithms: "r' U' R U' R' U2' r",
    pattern: ["CC", "CR", "BC", "BR", "S-TL", "S-TC", "S-LC", "S-LB", "S-RT"],
    algorithms: [],
    category: OLLCategory.SQUARE_SHAPES,
  },
  {
    id: "6",
    name: "6",
    setupAlgorithms: "r U R' U R U2' r'",
    pattern: ["CC", "TC", "TR", "CR", "S-LT", "S-LC", "S-BL", "S-BC", "S-RB"],
    algorithms: [],
    category: OLLCategory.SQUARE_SHAPES,
  },
  {
    id: "7",
    name: "7",
    setupAlgorithms: "r U2' R' U' R U' r'",
    pattern: ["CC", "TC", "CL", "BL", "S-TL", "S-BC", "S-BR", "S-RT", "S-RC"],
    algorithms: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "8",
    name: "8",
    setupAlgorithms: "r' U2' R U R' U r y2'",
    pattern: ["CC", "TC", "CR", "BR", "S-TR", "S-LT", "S-LC", "S-BL", "S-BC"],
    algorithms: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "9",
    name: "9",
    setupAlgorithms: "F U R U' R2' F' R U R U' R' y'",
    pattern: ["CC", "TR", "CL", "BC", "S-TC", "S-LT", "S-BL", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "10",
    name: "10",
    setupAlgorithms: "R U2' R' F R' F' R U' R U' R'",
    pattern: ["CC", "TR", "CL", "BC", "S-TL", "S-TC", "S-LB", "S-BR", "S-RC"],
    algorithms: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "11",
    name: "11",
    setupAlgorithms: "M U' R U2' R' U' R U' R2' r",
    pattern: ["CC", "CR", "BL", "BC", "S-TL", "S-TC", "S-LC", "S-BR", "S-RT"],
    algorithms: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "12",
    name: "12",
    setupAlgorithms: "F U R U' R' F' U' F U R U' R' F'",
    pattern: ["CC", "TR", "CR", "BC", "S-TC", "S-LT", "S-LC", "S-BL", "S-RB"],
    algorithms: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "13",
    name: "13",
    setupAlgorithms: "F' U' F r U' r' U r U r'",
    pattern: ["CC", "CL", "CR", "BL", "S-TL", "S-TC", "S-BC", "S-BR", "S-RT"],
    algorithms: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "14",
    name: "14",
    setupAlgorithms: "F U F' R' F R U' R' F' R",
    pattern: ["CC", "CL", "CR", "BR", "S-TR", "S-TC", "S-BC", "S-BL", "S-LT"],
    algorithms: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "15",
    name: "15",
    setupAlgorithms: "r' U' r U' R' U R r' U r",
    pattern: ["CC", "CL", "CR", "BR", "S-TL", "S-TC", "S-LB", "S-BC", "S-RT"],
    algorithms: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "16",
    name: "16",
    setupAlgorithms: "r U r' U R U' R' r U' r'",
    pattern: ["CC", "CL", "CR", "TR", "S-TC", "S-LT", "S-BL", "S-BC", "S-RB"],
    algorithms: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "17",
    name: "17",
    setupAlgorithms: "F R' F' R U2' F R' F' R U' R U' R'",
    pattern: ["CC", "TL", "BR", "S-TC", "S-TR", "S-LC", "S-LB", "S-BC", "S-RC"],
    algorithms: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "18",
    name: "18",
    setupAlgorithms: "r' U2' R U R' U r2' U2' R' U' R U' r'",
    pattern: [
      "CC",
      "TL",
      "TR",
      "S-TC",
      "S-LC",
      "S-RC",
      "S-RC",
      "S-BL",
      "S-BC",
      "S-BR",
    ],
    algorithms: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "19",
    name: "19",
    setupAlgorithms: "F R' F' R M U R U' R' U' M'",
    pattern: ["CC", "TL", "TR", "S-TC", "S-LC", "S-LB", "S-RC", "S-RB", "S-BC"],
    algorithms: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "20",
    name: "20",
    setupAlgorithms: "r U R' U' M2' U R U' R' U' M'",
    pattern: ["CC", "TL", "TR", "BL", "BR", "S-TC", "S-LC", "S-BC", "S-RC"],
    algorithms: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "21",
    name: "21",
    setupAlgorithms: "R U R' U R U' R' U R U2' R' y'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "S-LT", "S-LB", "S-RT", "S-RB"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "22",
    name: "22",
    setupAlgorithms: "R' U2' R2' U R2' U R2' U2' R'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "S-LT", "S-LB", "S-TR", "S-BR"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "23",
    name: "23",
    setupAlgorithms: "R U2' R D R' U2' R D' R2'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "TL", "TR", "S-BL", "S-BR"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "24",
    name: "24",
    setupAlgorithms: "F R' F' r U R U' r'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "TR", "BR", "S-TL", "S-BL"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "25",
    name: "25",
    setupAlgorithms: "R' F' r U R U' r' F y'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "TL", "BR", "S-BL", "S-RT"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "26",
    name: "26",
    setupAlgorithms: "R U R' U R U2' R' y'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "TL", "S-TR", "S-RB", "S-BL"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "27",
    name: "27",
    setupAlgorithms: "R U2' R' U' R U' R'",
    pattern: ["CC", "TC", "CL", "BC", "CR", "BL", "S-TL", "S-RT", "S-BR"],
    algorithms: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "28",
    name: "28",
    setupAlgorithms: "R U R' U' M' U R U' r'",
    pattern: ["CC", "TL", "TC", "TR", "CL", "BL", "BR", "S-RC", "S-BC"],
    algorithms: [],
    category: OLLCategory.ALL_CORNERS_ORIENTED,
  },
  {
    id: "29",
    name: "29",
    setupAlgorithms: "M F R' F' R U R U' R' U' M'",
    pattern: ["CC", "TL", "TR", "CL", "BC", "S-TC", "S-LB", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "30",
    name: "30",
    setupAlgorithms: "F U R U2' R' U R U2' R' U' F' y2'",
    pattern: ["CC", "TL", "TR", "CR", "BC", "S-TC", "S-RB", "S-LC", "S-LB"],
    algorithms: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "31",
    name: "31",
    setupAlgorithms: "R' F R U R' U' F' U R",
    pattern: ["CC", "TC", "TR", "CR", "BR", "S-TL", "S-LC", "S-BL", "S-BC"],
    algorithms: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "32",
    name: "32",
    setupAlgorithms: "f R' F' R U R U' R' S'",
    pattern: ["CC", "BC", "TR", "CR", "BR", "S-TL", "S-TC", "S-LC", "S-BL"],
    algorithms: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "33",
    name: "33",
    setupAlgorithms: "F R' F' R U R U' R'",
    pattern: ["CC", "TR", "CL", "CR", "BR", "S-TL", "S-TC", "S-BL", "S-BC"],
    algorithms: [],
    category: OLLCategory.T_SHAPES,
  },
  {
    id: "34",
    name: "34",
    setupAlgorithms: "F U R' U' R' F' R U R2' U' R' y2'",
    pattern: ["CC", "TL", "TR", "CL", "CR", "S-TC", "S-LB", "S-BC", "S-RB"],
    algorithms: [],
    category: OLLCategory.C_SHAPES,
  },
  {
    id: "35",
    name: "35",
    setupAlgorithms: "R U2' R' F R' F' R2' U2' R'",
    pattern: ["CC", "TL", "CR", "BC", "BR", "S-TC", "S-RT", "S-LC", "S-BL"],
    algorithms: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "36",
    name: "36",
    setupAlgorithms: "F' L F L' U' L' U' L U L' U L y2'",
    pattern: ["CC", "TL", "CL", "BC", "BR", "S-TC", "S-RT", "S-RC", "S-BL"],
    algorithms: [],
    category: OLLCategory.W_SHAPES,
  },
  {
    id: "37",
    name: "37",
    setupAlgorithms: "F R U' R' U R U R' F'",
    pattern: ["CC", "TL", "TC", "CL", "BR", "S-RT", "S-RC", "S-BL", "S-BC"],
    algorithms: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "38",
    name: "38",
    setupAlgorithms: "F R' F' R U R U R' U' R U' R'",
    pattern: ["CC", "TC", "TR", "CL", "BL", "S-TL", "S-RC", "S-RB", "S-BC"],
    algorithms: [],
    category: OLLCategory.W_SHAPES,
  },
  {
    id: "39",
    name: "39",
    setupAlgorithms: "L U F' U' L' U L F L' y'",
    pattern: ["CC", "TL", "TC", "BC", "BR", "S-TR", "S-RC", "S-LC", "S-LB"],
    algorithms: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "40",
    name: "40",
    setupAlgorithms: "R' U' F U R U' R' F' R y'",
    pattern: ["CC", "TR", "TC", "BC", "BL", "S-LT", "S-LC", "S-RC", "S-BR"],
    algorithms: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "41",
    name: "41",
    setupAlgorithms: "F U R U' R' F' R U2' R' U' R U' R' y2'",
    pattern: ["CC", "TL", "TR", "CR", "BC", "S-TC", "S-LC", "S-BL", "S-BR"],
    algorithms: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "42",
    name: "42",
    setupAlgorithms: "F U R U' R' F' R' U2' R U R' U R",
    pattern: ["CC", "TL", "TR", "CL", "BC", "S-TC", "S-RC", "S-BL", "S-BR"],
    algorithms: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "43",
    name: "43",
    setupAlgorithms: "f' U' L' U L f",
    pattern: ["CC", "TL", "CL", "BL", "BC", "S-TC", "S-RT", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "44",
    name: "44",
    setupAlgorithms: "f U R U' R' f'",
    pattern: ["CC", "TR", "CR", "BR", "BC", "S-TC", "S-LT", "S-LC", "S-LB"],
    algorithms: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "45",
    name: "45",
    setupAlgorithms: "F U R U' R' F'",
    pattern: ["CC", "TR", "CL", "CR", "BR", "S-TC", "S-BC", "S-LT", "S-LB"],
    algorithms: [],
    category: OLLCategory.T_SHAPES,
  },
  {
    id: "46",
    name: "46",
    setupAlgorithms: "R' U' F R' F' R U R",
    pattern: ["CC", "TL", "TC", "BL", "BC", "S-LC", "S-RT", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.C_SHAPES,
  },
  {
    id: "47",
    name: "47",
    setupAlgorithms: "F' U' L' U L U' L' U L F",
    pattern: ["CC", "TC", "CR", "S-TL", "S-LC", "S-RT", "S-RB", "S-BL", "S-BC"],
    algorithms: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "48",
    name: "48",
    setupAlgorithms: "F U R U' R' U R U' R' F'",
    pattern: ["CC", "TC", "CL", "S-TR", "S-RC", "S-LT", "S-LB", "S-BR", "S-BC"],
    algorithms: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "49",
    name: "49",
    setupAlgorithms: "r' U r2' U' r2' U' r2' U r' y2'",
    pattern: ["CC", "BC", "CL", "S-TL", "S-TC", "S-BL", "S-RT", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "50",
    name: "50",
    setupAlgorithms: "r U' r2' U r2' U r2' U' r",
    pattern: ["CC", "BC", "CR", "S-TR", "S-TC", "S-BR", "S-LT", "S-LC", "S-LB"],
    algorithms: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "51",
    name: "51",
    setupAlgorithms: "f U R U' R' U R U' R' f'",
    pattern: ["CC", "CL", "CR", "S-TC", "S-TR", "S-LT", "S-LB", "S-BC", "S-BR"],
    algorithms: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "52",
    name: "52",
    setupAlgorithms: "F R U R' d R' U' R U' R'",
    pattern: ["CC", "TC", "BC", "S-TL", "S-LC", "S-BL", "S-RT", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "53",
    name: "53",
    setupAlgorithms: "r' U2' R U R' U' R U R' U r",
    pattern: ["CC", "BC", "CR", "S-TC", "S-RT", "S-RB", "S-LT", "S-LC", "S-LB"],
    algorithms: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "54",
    name: "54",
    setupAlgorithms: "r U2' R' U' R U R' U' R U' r'",
    pattern: ["CC", "TC", "CR", "S-BC", "S-RT", "S-RB", "S-LT", "S-LC", "S-LB"],
    algorithms: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "55",
    name: "55",
    setupAlgorithms: "F R' F' U2' R U R' U R2' U2' R'",
    pattern: ["CC", "TC", "BC", "S-LT", "S-LC", "S-LB", "S-RT", "S-RC", "S-RB"],
    algorithms: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "56",
    name: "56",
    setupAlgorithms: "r U r' R U R' U' R U R' U' r U' r'",
    pattern: ["CC", "CL", "CR", "S-TC", "S-BC", "S-LT", "S-LB", "S-RT", "S-RB"],
    algorithms: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "57",
    name: "57",
    setupAlgorithms: "r U R' U' M U R U' R'",
    pattern: ["CC", "TL", "CL", "BL", "TR", "CR", "BR", "S-TC", "S-BC"],
    algorithms: [],
    category: OLLCategory.ALL_CORNERS_ORIENTED,
  },
];

export const definitionMap = new Map(
  definitions.map((definition) => [definition.id, definition]),
);
