import type { PLLDefinition } from "@/schema/cube/333";
import { PLLCategory } from "@/schema/cube/enum/333";

const definitions: PLLDefinition[] = [
  {
    id: "PLL_Aa",
    name: "Aa",
    setupAlgorithms: [
      "x",
      "R2'",
      "D2'",
      "R",
      "U",
      "R'",
      "D2'",
      "R",
      "U'",
      "R",
      "x'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Ab",
    name: "Ab",
    setupAlgorithms: [
      "x",
      "R'",
      "U",
      "R'",
      "D2'",
      "R",
      "U'",
      "R'",
      "D2'",
      "R2'",
      "x'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_E",
    name: "E",
    setupAlgorithms: [
      "x'",
      "D",
      "R",
      "U",
      "R'",
      "D'",
      "R",
      "U'",
      "R'",
      "D",
      "R",
      "U'",
      "R'",
      "D'",
      "R",
      "U",
      "R'",
      "x",
      "y'",
    ],
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "PLL_F",
    name: "F",
    setupAlgorithms: [
      "R'",
      "U'",
      "R",
      "U'",
      "R'",
      "U",
      "R",
      "U",
      "R2'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
      "F",
      "U",
      "R",
      "y'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Ga",
    name: "Ga",
    setupAlgorithms: [
      "R'",
      "U'",
      "R",
      "D'",
      "U",
      "R2'",
      "U",
      "R'",
      "U",
      "R",
      "U'",
      "R",
      "U'",
      "R2'",
      "D",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Gb",
    name: "Gb",
    setupAlgorithms: [
      "R2'",
      "U",
      "R'",
      "U",
      "R'",
      "U'",
      "R",
      "U'",
      "R2'",
      "D",
      "U'",
      "R'",
      "U",
      "R",
      "D'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Gc",
    name: "Gc",
    setupAlgorithms: [
      "D'",
      "R",
      "U",
      "R'",
      "U'",
      "D",
      "R2'",
      "U'",
      "R",
      "U'",
      "R'",
      "U",
      "R'",
      "U",
      "R2'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Gd",
    name: "Gd",
    setupAlgorithms: [
      "R2'",
      "U'",
      "R",
      "U'",
      "R",
      "U",
      "R'",
      "U",
      "R2'",
      "D'",
      "U",
      "R",
      "U'",
      "R'",
      "D",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_H",
    name: "H",
    setupAlgorithms: ["M2'", "U'", "M2'", "U2'", "M2'", "U'", "M2'"],
    patternColors: {},
    category: PLLCategory.EPLL,
  },
  {
    id: "PLL_Ja",
    name: "Ja",
    setupAlgorithms: [
      "L'",
      "R'",
      "U2'",
      "R",
      "U",
      "R'",
      "U2'",
      "L",
      "U'",
      "R",
      "y'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Jb",
    name: "Jb",
    setupAlgorithms: [
      "R",
      "U",
      "R2'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
      "F",
      "R",
      "U'",
      "R'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Na",
    name: "Na",
    setupAlgorithms: [
      "R",
      "U",
      "R'",
      "U2'",
      "R",
      "U",
      "R2'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
      "F",
      "R",
      "U'",
      "R'",
      "U'",
      "R",
      "U'",
      "R'",
    ],
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "PLL_Nb",
    name: "Nb",
    setupAlgorithms: [
      "F",
      "r'",
      "F'",
      "r",
      "U",
      "r",
      "U'",
      "r2'",
      "D'",
      "F",
      "r",
      "U",
      "r'",
      "F'",
      "D",
      "r",
    ],
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "PLL_Ra",
    name: "Ra",
    setupAlgorithms: [
      "R",
      "U2'",
      "R",
      "D",
      "R'",
      "U",
      "R",
      "D'",
      "R'",
      "U'",
      "R'",
      "U",
      "R",
      "U",
      "R'",
      "y'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Rb",
    name: "Rb",
    setupAlgorithms: [
      "R'",
      "U",
      "R",
      "U",
      "R'",
      "U'",
      "R'",
      "D'",
      "R",
      "U",
      "R'",
      "D",
      "R",
      "U2'",
      "R",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_T",
    name: "T",
    setupAlgorithms: [
      "F",
      "R",
      "U'",
      "R'",
      "U",
      "R",
      "U",
      "R2'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
    ],
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "PLL_Ua",
    name: "Ua",
    setupAlgorithms: ["M2'", "U'", "M'", "U2'", "M", "U'", "M2'"],
    patternColors: {},
    category: PLLCategory.EPLL,
  },
  {
    id: "PLL_Ub",
    name: "Ub",
    setupAlgorithms: ["M2'", "U", "M'", "U2'", "M", "U", "M2'"],
    patternColors: {},
    category: PLLCategory.EPLL,
  },
  {
    id: "PLL_V",
    name: "V",
    setupAlgorithms: [
      "D2'",
      "R'",
      "U",
      "R",
      "D'",
      "R2'",
      "U'",
      "R'",
      "U",
      "R'",
      "U",
      "R'",
      "D'",
      "R",
      "U2'",
      "R'",
    ],
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "PLL_Y",
    name: "Y",
    setupAlgorithms: [
      "F",
      "R'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
      "F",
      "R",
      "U'",
      "R'",
      "U",
      "R",
      "U",
      "R'",
      "F'",
    ],
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "PLL_Z",
    name: "Z",
    setupAlgorithms: ["M", "U2'", "M2'", "U2'", "M", "U'", "M2'", "U'", "M2'"],
    patternColors: {},
    category: PLLCategory.EPLL,
  },
];

export default definitions;
