import type { PLLDefinition } from "@/schema/cube/333";
import { PLLCategory } from "@/schema/cube/enum/333";

const definitions: PLLDefinition[] = [
  {
    id: "Aa",
    name: "Aa",
    setupAlgorithms: "x R2' D2' R U R' D2' R U' R x'",
    patternColors: {
      "S-TL": "R",
      "S-TC": "B",
      "S-TR": "R",
      "S-LT": "B",
      "S-LC": "L",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "B",
      "S-RT": "F",
      "S-RC": "R",
      "S-RB": "L",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Ab",
    name: "Ab",
    setupAlgorithms: "x R' U R' D2' R U' R' D2' R2' x'",
    patternColors: {
      "S-TL": "F",
      "S-TC": "B",
      "S-TR": "L",
      "S-LT": "R",
      "S-LC": "L",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "R",
      "S-RT": "B",
      "S-RC": "R",
      "S-RB": "B",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "E",
    name: "E",
    setupAlgorithms: "x' D R U R' D' R U' R' D R U' R' D' R U R' x y'",
    patternColors: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "B",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "L",
      "S-BR": "B",
      "S-RT": "R",
      "S-RC": "F",
      "S-RB": "L",
    },
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "F",
    name: "F",
    setupAlgorithms: "R' U' R U' R' U R U R2' F' R U R U' R' F U R y'",
    patternColors: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "F",
      "S-LB": "B",
      "S-BL": "L",
      "S-BC": "L",
      "S-BR": "L",
      "S-RT": "R",
      "S-RC": "B",
      "S-RB": "F",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Ga",
    name: "Ga",
    setupAlgorithms: "R' U' R D' U R2' U R' U R U' R U' R2' D",
    patternColors: {
      "S-TL": "B",
      "S-TC": "F",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "B",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "L",
      "S-BR": "L",
      "S-RT": "F",
      "S-RC": "L",
      "S-RB": "B",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Gb",
    name: "Gb",
    setupAlgorithms: "R2' U R' U R' U' R U' R2' D U' R' U R D'",
    patternColors: {
      "S-TL": "B",
      "S-TC": "L",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "B",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "F",
      "S-RB": "B",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Gc",
    name: "Gc",
    setupAlgorithms: "D' R U R' U' D R2' U' R U' R' U R' U R2'",
    patternColors: {
      "S-TL": "B",
      "S-TC": "R",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "F",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "B",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "R",
      "S-RB": "B",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Gd",
    name: "Gd",
    setupAlgorithms: "R2' U' R U' R U R' U R2' D' U R U' R' D",
    patternColors: {
      "S-TL": "B",
      "S-TC": "F",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "L",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "B",
      "S-RB": "B",
    },
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "H",
    name: "H",
    setupAlgorithms: "M2' U' M2' U2' M2' U' M2'",
    patternColors: {
      "S-TL": "B",
      "S-TC": "F",
      "S-TR": "B",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "B",
      "S-BR": "F",
      "S-RT": "R",
      "S-RC": "L",
      "S-RB": "R",
    },
    category: PLLCategory.EPLL,
  },
  {
    id: "Ja",
    name: "Ja",
    setupAlgorithms: "L' R' U2' R U R' U2' L U' R y'",
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Jb",
    name: "Jb",
    setupAlgorithms: "R U R2' F' R U R U' R' F R U' R'",
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Na",
    name: "Na",
    setupAlgorithms: "R U R' U2' R U R2' F' R U R U' R' F R U' R' U' R U' R'",
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Nb",
    name: "Nb",
    setupAlgorithms: "F r' F' r U r U' r2' D' F r U r' F' D r",
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Ra",
    name: "Ra",
    setupAlgorithms: "R U2' R D R' U R D' R' U' R' U R U R' y'",
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Rb",
    name: "Rb",
    setupAlgorithms: "R' U R U R' U' R' D' R U R' D R U2' R",
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "T",
    name: "T",
    setupAlgorithms: "F R' F' R U R U R2' F' R U R U' R'",
    patternColors: {},
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Ua",
    name: "Ua",
    setupAlgorithms: "M2' U' M' U2' M U' M2'",
    patternColors: {},
    category: PLLCategory.EPLL,
  },
  {
    id: "Ub",
    name: "Ub",
    setupAlgorithms: "M2' U M' U2' M U M2'",
    patternColors: {},
    category: PLLCategory.EPLL,
  },
  {
    id: "V",
    name: "V",
    setupAlgorithms: "D2' R' U R D' R2' U' R' U R' U R' D' R U2' R'",
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Y",
    name: "Y",
    setupAlgorithms: "F R' F' R U R U' R' F R U' R' U R U R' F'",
    patternColors: {},
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Z",
    name: "Z",
    setupAlgorithms: "M U2' M2' U2' M U' M2' U' M2'",
    patternColors: {},
    category: PLLCategory.EPLL,
  },
];

export default definitions;
