import type { F2LDefinition } from "@/types/cube/333";
import { F2LCategory } from "@/enums/cube/333";

export type { F2LDefinition, F2LCaseId } from "@/types/cube/333";

/** 固定上色 */
const fixedPattern: Pick<
  F2LDefinition["pattern"],
  "F-CC" | "F-CL" | "F-BL" | "F-BC" | "S-CC" | "S-CR" | "S-BC" | "S-BR"
> = {
  "F-CC": "F",
  "F-CL": "F",
  "F-BL": "F",
  "F-BC": "F",
  "S-CC": "R",
  "S-CR": "R",
  "S-BC": "R",
  "S-BR": "R",
};

export const definitions: F2LDefinition[] = [
  {
    id: "1",
    name: "1",
    setupAlgorithms: "F R' F' R",
    category: F2LCategory.FREE_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CR": "F",
      "U-BR": "F",
      "F-TR": "D",
      "S-TL": "R",
      "S-TC": "R",
    },
  },
  {
    id: "2",
    name: "2",
    setupAlgorithms: "R' F R F'",
    category: F2LCategory.FREE_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-BC": "R",
      "U-BR": "R",
      "F-TC": "F",
      "F-TR": "F",
      "S-TL": "D",
    },
  },
  {
    id: "3",
    name: "3",
    setupAlgorithms: "F' U F",
    category: F2LCategory.FREE_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CL": "R",
      "U-BR": "F",
      "F-TR": "D",
      "S-TL": "R",
    },
  },
  {
    id: "4",
    name: "4",
    setupAlgorithms: "R U' R'",
    category: F2LCategory.FREE_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-TC": "F",
      "U-BR": "R",
      "F-TR": "F",
      "S-TL": "D",
    },
  },
  {
    id: "5",
    name: "5",
    setupAlgorithms: "R U R' U2' R U' R' U",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-TC": "F",
      "U-BR": "F",
      "F-TR": "D",
      "S-TL": "R",
    },
  },
  {
    id: "6",
    name: "6",
    setupAlgorithms: "F' U' F U2' F' U F U'",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CL": "R",
      "U-BR": "R",
      "F-TR": "F",
      "S-TL": "D",
    },
  },
  {
    id: "7",
    name: "7",
    setupAlgorithms: "R U R' U2' R U2' R' U",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CL": "F",
      "U-BR": "F",
      "F-TR": "D",
      "S-TL": "R",
    },
  },
  {
    id: "8",
    name: "8",
    setupAlgorithms: "r' U' R2 U' R2' U2' r",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-TC": "R",
      "U-BR": "R",
      "F-TR": "F",
      "S-TL": "D",
    },
  },
  {
    id: "9",
    name: "9",
    setupAlgorithms: "F' U F U' R U R' U",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-TC": "R",
      "U-BR": "F",
      "F-TR": "D",
      "S-TL": "R",
    },
  },
  {
    id: "10",
    name: "10",
    setupAlgorithms: "R U' R' U' R U' R' U",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CL": "F",
      "U-BR": "R",
      "F-TR": "F",
      "S-TL": "D",
    },
  },
  {
    id: "11",
    name: "11",
    setupAlgorithms: "F' U F U' R U2' R' U",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CR": "R",
      "U-BR": "F",
      "F-TR": "D",
      "S-TL": "R",
      "S-TC": "F",
    },
  },
  {
    id: "12",
    name: "12",
    setupAlgorithms: "R U R' U2' R U R' U' R U R'",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-BC": "F",
      "U-BR": "R",
      "F-TC": "R",
      "F-TR": "F",
      "S-TL": "D",
    },
  },
  {
    id: "13",
    name: "13",
    setupAlgorithms: "r U2' R' U R U' R' U M",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-BC": "R",
      "U-BR": "F",
      "F-TC": "F",
      "F-TR": "D",
      "S-TL": "R",
    },
  },
  {
    id: "14",
    name: "14",
    setupAlgorithms: "R U' R' U' R U R' U",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CR": "F",
      "U-BR": "R",
      "F-TR": "F",
      "S-TL": "D",
      "S-TC": "R",
    },
  },
  {
    id: "15",
    name: "15",
    setupAlgorithms: "R U R' U' R U R' U2' R U' R'",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-BC": "F",
      "U-BR": "F",
      "F-TC": "R",
      "F-TR": "D",
      "S-TL": "R",
    },
  },
  {
    id: "16",
    name: "16",
    setupAlgorithms: "F' U F U2' R U R'",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CR": "R",
      "U-BR": "R",
      "F-TR": "F",
      "S-TL": "D",
      "S-TC": "F",
    },
  },
  {
    id: "17",
    name: "17",
    setupAlgorithms: "R U' R' U R U2' R'",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CR": "F",
      "U-BR": "D",
      "F-TR": "R",
      "S-TL": "F",
      "S-TC": "R",
    },
  },
  {
    id: "18",
    name: "18",
    setupAlgorithms: "R U R' U' R U R' F R' F' R",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-BC": "R",
      "U-BR": "D",
      "F-TC": "F",
      "F-TR": "R",
      "S-TL": "F",
    },
  },
  {
    id: "19",
    name: "19",
    setupAlgorithms: "R U R' U' R U2' R' U'",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-TC": "F",
      "U-BR": "D",
      "F-TR": "R",
      "S-TL": "F",
    },
  },
  {
    id: "20",
    name: "20",
    setupAlgorithms: "R U R' F R' F' R2' U R' U",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CL": "R",
      "U-BR": "D",
      "F-TR": "R",
      "S-TL": "F",
    },
  },
  {
    id: "21",
    name: "21",
    setupAlgorithms: "R U' R' U2' R U R'",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CL": "F",
      "U-BR": "D",
      "F-TR": "R",
      "S-TL": "F",
    },
  },
  {
    id: "22",
    name: "22",
    setupAlgorithms: "F' L' U2' L F",
    category: F2LCategory.DISCONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-TC": "R",
      "U-BR": "D",
      "F-TR": "R",
      "S-TL": "F",
    },
  },
  {
    id: "23",
    name: "23",
    setupAlgorithms: "R U' R' U R U' R' U2' R U' R'",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-BC": "F",
      "U-BR": "D",
      "F-TC": "R",
      "F-TR": "R",
      "S-TL": "F",
    },
  },
  {
    id: "24",
    name: "24",
    setupAlgorithms: "R U R' F R U R' U' F'",
    category: F2LCategory.CONNECTED_PAIRS,
    pattern: {
      ...fixedPattern,
      "U-CR": "R",
      "U-BR": "D",
      "F-TR": "R",
      "S-TL": "F",
      "S-TC": "F",
    },
  },
  {
    id: "25",
    name: "25",
    setupAlgorithms: "F' R U R' U' R' F R",
    category: F2LCategory.CORNER_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-CR": "F",
      "F-BR": "F",
      "S-TC": "R",
      "S-BL": "R",
    },
  },
  {
    id: "26",
    name: "26",
    setupAlgorithms: "F' U' F U R U R' U'",
    category: F2LCategory.CORNER_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BC": "R",
      "F-TC": "F",
      "F-BR": "F",
      "S-BL": "R",
    },
  },
  {
    id: "27",
    name: "27",
    setupAlgorithms: "R U R' U' R U R'",
    category: F2LCategory.CORNER_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-CR": "F",
      "F-BR": "D",
      "S-TC": "R",
      "S-BL": "F",
    },
  },
  {
    id: "28",
    name: "28",
    setupAlgorithms: "R' F R F' U R U' R'",
    category: F2LCategory.CORNER_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BC": "R",
      "F-TC": "F",
      "F-BR": "R",
      "S-BL": "D",
    },
  },
  {
    id: "29",
    name: "29",
    setupAlgorithms: "F R' F' R F R' F' R",
    category: F2LCategory.CORNER_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BC": "R",
      "F-TC": "F",
      "F-BR": "D",
      "S-BL": "F",
    },
  },
  {
    id: "30",
    name: "30",
    setupAlgorithms: "R U' R' U R U' R'",
    category: F2LCategory.CORNER_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-CR": "F",
      "F-BR": "R",
      "S-TC": "R",
      "S-BL": "D",
    },
  },
  {
    id: "31",
    name: "31",
    setupAlgorithms: "R U R' F R' F' R U",
    category: F2LCategory.EDGE_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BR": "D",
      "F-TR": "R",
      "F-CR": "R",
      "S-TL": "F",
      "S-CL": "F",
    },
  },
  {
    id: "32",
    name: "32",
    setupAlgorithms: "R U' R' U R U' R' U R U' R'",
    category: F2LCategory.EDGE_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BR": "D",
      "F-TR": "R",
      "F-CR": "F",
      "S-TL": "F",
      "S-CL": "R",
    },
  },
  {
    id: "33",
    name: "33",
    setupAlgorithms: "R U R' U2' R U R' U",
    category: F2LCategory.EDGE_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BR": "F",
      "F-TR": "D",
      "F-CR": "F",
      "S-TL": "R",
      "S-CL": "R",
    },
  },
  {
    id: "34",
    name: "34",
    setupAlgorithms: "R U' R' U2' R U' R' U'",
    category: F2LCategory.EDGE_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BR": "R",
      "F-TR": "F",
      "F-CR": "F",
      "S-TL": "D",
      "S-CL": "R",
    },
  },
  {
    id: "35",
    name: "35",
    setupAlgorithms: "F' U F U' R U' R' U",
    category: F2LCategory.EDGE_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BR": "F",
      "F-TR": "D",
      "F-CR": "R",
      "S-TL": "R",
      "S-CL": "F",
    },
  },
  {
    id: "36",
    name: "36",
    setupAlgorithms: "R U' R' U2' F R' F' R U2'",
    category: F2LCategory.EDGE_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "U-BR": "R",
      "F-TR": "F",
      "F-CR": "R",
      "S-TL": "D",
      "S-CL": "F",
    },
  },
  {
    id: "37",
    name: "37",
    setupAlgorithms: "R U' R U2' F R2' F' U2' R2'",
    category: F2LCategory.PIECES_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "F-CR": "R",
      "F-BR": "F",
      "S-CL": "F",
      "S-BL": "R",
    },
  },
  {
    id: "38",
    name: "38",
    setupAlgorithms: "R U' R' U R U2' R' U R U' R'",
    category: F2LCategory.PIECES_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "F-CR": "F",
      "F-BR": "D",
      "S-CL": "R",
      "S-BL": "F",
    },
  },
  {
    id: "39",
    name: "39",
    setupAlgorithms: "R U' R' U' R U R' U2' R U' R'",
    category: F2LCategory.PIECES_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "F-CR": "F",
      "F-BR": "R",
      "S-CL": "R",
      "S-BL": "D",
    },
  },
  {
    id: "40",
    name: "40",
    setupAlgorithms: "R U R' F U R U' R' F' R U R'",
    category: F2LCategory.PIECES_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "F-CR": "R",
      "F-BR": "D",
      "S-CL": "F",
      "S-BL": "F",
    },
  },
  {
    id: "41",
    name: "41",
    setupAlgorithms: "R F U R U' R' F' U' R'",
    category: F2LCategory.PIECES_IN_SLOT,
    pattern: {
      ...fixedPattern,
      "F-CR": "R",
      "F-BR": "R",
      "S-CL": "F",
      "S-BL": "D",
    },
  },
];

export const definitionMap = new Map(
  definitions.map((definition) => [definition.id, definition]),
);
