import type { OLLDefinition } from "@/schema/cube/333";
import { OLLCategory } from "@/schema/cube/enum/333";

const definitions: OLLDefinition[] = [
  {
    id: "1",
    name: "OLL-1",
    setupAlgorithms: "F R' F' R U2' F R' F' R2' U2' R'",
    patternPositions: [
      "CC",
      "S-TC",
      "S-LT",
      "S-LC",
      "S-LB",
      "S-BC",
      "S-RT",
      "S-RC",
      "S-RB",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "2",
    name: "OLL-2",
    setupAlgorithms: "f U R U' R' f' F U R U' R' F'",
    patternPositions: [
      "CC",
      "S-TC",
      "S-TR",
      "S-LT",
      "S-LC",
      "S-LB",
      "S-BC",
      "S-BR",
      "S-RC",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "3",
    name: "OLL-3",
    setupAlgorithms: "F U R U' R' F' U f U R U' R' f' y",
    patternPositions: [
      "CC",
      "BL",
      "S-TL",
      "S-TC",
      "S-LC",
      "S-BC",
      "S-BR",
      "S-RT",
      "S-RC",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "4",
    name: "OLL-4",
    setupAlgorithms: "F U R U' R' F' U' f U R U' R' f' y",
    patternPositions: [
      "CC",
      "BR",
      "S-TC",
      "S-TR",
      "S-LT",
      "S-LC",
      "S-BL",
      "S-BC",
      "S-RC",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "5",
    name: "OLL-5",
    setupAlgorithms: "r' U' R U' R' U2' r",
    patternPositions: [
      "CC",
      "CR",
      "BC",
      "BR",
      "S-TL",
      "S-TC",
      "S-LC",
      "S-LB",
      "S-RT",
    ],
    category: OLLCategory.SQUARE_SHAPES,
  },
  {
    id: "6",
    name: "OLL-6",
    setupAlgorithms: "r U R' U R U2' r'",
    patternPositions: [
      "CC",
      "TC",
      "TR",
      "CR",
      "S-LT",
      "S-LC",
      "S-BL",
      "S-BC",
      "S-RB",
    ],
    category: OLLCategory.SQUARE_SHAPES,
  },
  {
    id: "7",
    name: "OLL-7",
    setupAlgorithms: "r U2' R' U' R U' r'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BL",
      "S-TL",
      "S-BC",
      "S-BR",
      "S-RT",
      "S-RC",
    ],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "8",
    name: "OLL-8",
    setupAlgorithms: "r' U2' R U R' U r y2'",
    patternPositions: [
      "CC",
      "TC",
      "CR",
      "BR",
      "S-TR",
      "S-LT",
      "S-LC",
      "S-BL",
      "S-BC",
    ],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "9",
    name: "OLL-9",
    setupAlgorithms: "F U R U' R2' F' R U R U' R' y'",
    patternPositions: [
      "CC",
      "TR",
      "CL",
      "BC",
      "S-TC",
      "S-LT",
      "S-BL",
      "S-RC",
      "S-RB",
    ],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "10",
    name: "OLL-10",
    setupAlgorithms: "R U2' R' F R' F' R U' R U' R'",
    patternPositions: [
      "CC",
      "TR",
      "CL",
      "BC",
      "S-TL",
      "S-TC",
      "S-LB",
      "S-BR",
      "S-RC",
    ],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "11",
    name: "OLL-11",
    setupAlgorithms: "M U' R U2' R' U' R U' R2' r",
    patternPositions: [
      "CC",
      "CR",
      "BL",
      "BC",
      "S-TL",
      "S-TC",
      "S-LC",
      "S-BR",
      "S-RT",
    ],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "12",
    name: "OLL-12",
    setupAlgorithms: "F U R U' R' F' U' F U R U' R' F'",
    patternPositions: [
      "CC",
      "TR",
      "CR",
      "BC",
      "S-TC",
      "S-LT",
      "S-LC",
      "S-BL",
      "S-RB",
    ],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "13",
    name: "OLL-13",
    setupAlgorithms: "F' U' F r U' r' U r U r'",
    patternPositions: [
      "CC",
      "CL",
      "CR",
      "BL",
      "S-TL",
      "S-TC",
      "S-BC",
      "S-BR",
      "S-RT",
    ],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "14",
    name: "OLL-14",
    setupAlgorithms: "F U F' R' F R U' R' F' R",
    patternPositions: [
      "CC",
      "CL",
      "CR",
      "BR",
      "S-TR",
      "S-TC",
      "S-BC",
      "S-BL",
      "S-LT",
    ],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "15",
    name: "OLL-15",
    setupAlgorithms: "r' U' r U' R' U R r' U r",
    patternPositions: [
      "CC",
      "CL",
      "CR",
      "BR",
      "S-TL",
      "S-TC",
      "S-LB",
      "S-BC",
      "S-RT",
    ],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "16",
    name: "OLL-16",
    setupAlgorithms: "r U r' U R U' R' r U' r'",
    patternPositions: [
      "CC",
      "CL",
      "CR",
      "TR",
      "S-TC",
      "S-LT",
      "S-BL",
      "S-BC",
      "S-RB",
    ],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "17",
    name: "OLL-17",
    setupAlgorithms: "F R' F' R U2' F R' F' R U' R U' R'",
    patternPositions: [
      "CC",
      "TL",
      "BR",
      "S-TC",
      "S-TR",
      "S-LC",
      "S-LB",
      "S-BC",
      "S-RC",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "18",
    name: "OLL-18",
    setupAlgorithms: "r' U2' R U R' U r2' U2' R' U' R U' r'",
    patternPositions: [
      "CC",
      "TL",
      "TR",
      "S-TC",
      "S-LC",
      "S-RC",
      "S-RC",
      "S-BL",
      "S-BC",
      "S-BR",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "19",
    name: "OLL-19",
    setupAlgorithms: "F R' F' R M U R U' R' U' M'",
    patternPositions: [
      "CC",
      "TL",
      "TR",
      "S-TC",
      "S-LC",
      "S-LB",
      "S-RC",
      "S-RB",
      "S-BC",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "20",
    name: "OLL-20",
    setupAlgorithms: "r U R' U' M2' U R U' R' U' M'",
    patternPositions: [
      "CC",
      "TL",
      "TR",
      "BL",
      "BR",
      "S-TC",
      "S-LC",
      "S-BC",
      "S-RC",
    ],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "21",
    name: "OLL-21",
    setupAlgorithms: "R U R' U R U' R' U R U2' R' y'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "S-LT",
      "S-LB",
      "S-RT",
      "S-RB",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "22",
    name: "OLL-22",
    setupAlgorithms: "R' U2' R2' U R2' U R2' U2' R'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "S-LT",
      "S-LB",
      "S-TR",
      "S-BR",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "23",
    name: "OLL-23",
    setupAlgorithms: "R U2' R D R' U2' R D' R2'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "TL",
      "TR",
      "S-BL",
      "S-BR",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "24",
    name: "OLL-24",
    setupAlgorithms: "F R' F' r U R U' r'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "TR",
      "BR",
      "S-TL",
      "S-BL",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "25",
    name: "OLL-25",
    setupAlgorithms: "R' F' r U R U' r' F y'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "TL",
      "BR",
      "S-BL",
      "S-RT",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "26",
    name: "OLL-26",
    setupAlgorithms: "R U R' U R U2' R' y'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "TL",
      "S-TR",
      "S-RB",
      "S-BL",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "27",
    name: "OLL-27",
    setupAlgorithms: "R U2' R' U' R U' R'",
    patternPositions: [
      "CC",
      "TC",
      "CL",
      "BC",
      "CR",
      "BL",
      "S-TL",
      "S-RT",
      "S-BR",
    ],
    category: OLLCategory.OCLL,
  },
  {
    id: "28",
    name: "OLL-28",
    setupAlgorithms: "R U R' U' M' U R U' r'",
    patternPositions: ["CC"],
    category: OLLCategory.ALL_CORNERS_ORIENTED,
  },
  {
    id: "29",
    name: "OLL-29",
    setupAlgorithms: "M F R' F' R U R U' R' U' M'",
    patternPositions: ["CC"],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "30",
    name: "OLL-30",
    setupAlgorithms: "F U R U2' R' U R U2' R' U' F' y2'",
    patternPositions: ["CC"],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "31",
    name: "OLL-31",
    setupAlgorithms: "R' F R U R' U' F' U R",
    patternPositions: ["CC"],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "32",
    name: "OLL-32",
    setupAlgorithms: "f R' F' R U R U' R' S'",
    patternPositions: ["CC"],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "33",
    name: "OLL-33",
    setupAlgorithms: "F R' F' R U R U' R'",
    patternPositions: ["CC"],
    category: OLLCategory.T_SHAPES,
  },
  {
    id: "34",
    name: "OLL-34",
    setupAlgorithms: "F U R' U' R' F' R U R2' U' R' y2'",
    patternPositions: ["CC"],
    category: OLLCategory.C_SHAPES,
  },
  {
    id: "35",
    name: "OLL-35",
    setupAlgorithms: "R U2' R' F R' F' R2' U2' R'",
    patternPositions: ["CC"],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "36",
    name: "OLL-36",
    setupAlgorithms: "F' L F L' U' L' U' L U L' U L y2'",
    patternPositions: ["CC"],
    category: OLLCategory.W_SHAPES,
  },
  {
    id: "37",
    name: "OLL-37",
    setupAlgorithms: "F R U' R' U R U R' F'",
    patternPositions: ["CC"],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "38",
    name: "OLL-38",
    setupAlgorithms: "F R' F' R U R U R' U' R U' R'",
    patternPositions: ["CC"],
    category: OLLCategory.W_SHAPES,
  },
  {
    id: "39",
    name: "OLL-39",
    setupAlgorithms: "L U F' U' L' U L F L' y'",
    patternPositions: ["CC"],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "40",
    name: "OLL-40",
    setupAlgorithms: "R' U' F U R U' R' F' R y'",
    patternPositions: ["CC"],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "41",
    name: "OLL-41",
    setupAlgorithms: "F U R U' R' F' R U2' R' U' R U' R' y2'",
    patternPositions: ["CC"],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "42",
    name: "OLL-42",
    setupAlgorithms: "F U R U' R' F' R' U2' R U R' U R",
    patternPositions: ["CC"],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "43",
    name: "OLL-43",
    setupAlgorithms: "f' U' L' U L f",
    patternPositions: ["CC"],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "44",
    name: "OLL-44",
    setupAlgorithms: "f U R U' R' f'",
    patternPositions: ["CC"],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "45",
    name: "OLL-45",
    setupAlgorithms: "F U R U' R' F'",
    patternPositions: ["CC"],
    category: OLLCategory.T_SHAPES,
  },
  {
    id: "46",
    name: "OLL-46",
    setupAlgorithms: "R' U' F R' F' R U R",
    patternPositions: ["CC"],
    category: OLLCategory.C_SHAPES,
  },
  {
    id: "47",
    name: "OLL-47",
    setupAlgorithms: "F' U' L' U L U' L' U L F",
    patternPositions: ["CC"],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "48",
    name: "OLL-48",
    setupAlgorithms: "F U R U' R' U R U' R' F'",
    patternPositions: ["CC"],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "49",
    name: "OLL-49",
    setupAlgorithms: "r' U r2' U' r2' U' r2' U r' y2'",
    patternPositions: ["CC"],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "50",
    name: "OLL-50",
    setupAlgorithms: "r U' r2' U r2' U r2' U' r",
    patternPositions: ["CC"],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "51",
    name: "OLL-51",
    setupAlgorithms: "f U R U' R' U R U' R' f'",
    patternPositions: ["CC"],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "52",
    name: "OLL-52",
    setupAlgorithms: "F R U R' d R' U' R U' R'",
    patternPositions: ["CC"],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "53",
    name: "OLL-53",
    setupAlgorithms: "r' U2' R U R' U' R U R' U r",
    patternPositions: ["CC"],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "54",
    name: "OLL-54",
    setupAlgorithms: "r U2' R' U' R U R' U' R U' r'",
    patternPositions: ["CC"],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "55",
    name: "OLL-55",
    setupAlgorithms: "F R' F' U2' R U R' U R2' U2' R'",
    patternPositions: ["CC"],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "56",
    name: "OLL-56",
    setupAlgorithms: "r U r' R U R' U' R U R' U' r U' r'",
    patternPositions: ["CC"],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "57",
    name: "OLL-57",
    setupAlgorithms: "r U R' U' M U R U' R'",
    patternPositions: ["CC"],
    category: OLLCategory.ALL_CORNERS_ORIENTED,
  },
];

export default definitions;
