import type { OLLDefinition } from "@/schema/cube/333";
import { OLLCategory } from "@/schema/cube/enum/333";

const definitions: OLLDefinition[] = [
  {
    id: "Oll_1",
    name: "OLL-1",
    setupAlgorithms: [
      "F",
      "R'",
      "F'",
      "R",
      "U2'",
      "F",
      "R'",
      "F'",
      "R2'",
      "U2'",
      "R'",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_2",
    name: "OLL-2",
    setupAlgorithms: [
      "f",
      "U",
      "R",
      "U'",
      "R'",
      "f'",
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_3",
    name: "OLL-3",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
      "U",
      "f",
      "U",
      "R",
      "U'",
      "R'",
      "f'",
      "y",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_4",
    name: "OLL-4",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
      "U'",
      "f",
      "U",
      "R",
      "U'",
      "R'",
      "f'",
      "y",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_5",
    name: "OLL-5",
    setupAlgorithms: ["r'", "U'", "R", "U'", "R'", "U2'", "r"],
    patternPositions: [],
    category: OLLCategory.SQUARE_SHAPES,
  },
  {
    id: "Oll_6",
    name: "OLL-6",
    setupAlgorithms: ["r", "U", "R'", "U", "R", "U2'", "r'"],
    patternPositions: [],
    category: OLLCategory.SQUARE_SHAPES,
  },
  {
    id: "Oll_7",
    name: "OLL-7",
    setupAlgorithms: ["r", "U2'", "R'", "U'", "R", "U'", "r'"],
    patternPositions: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "Oll_8",
    name: "OLL-8",
    setupAlgorithms: ["r'", "U2'", "R", "U", "R'", "U", "r", "y2'"],
    patternPositions: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "Oll_9",
    name: "OLL-9",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U'",
      "R2'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
      "y'",
    ],
    patternPositions: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "Oll_10",
    name: "OLL-10",
    setupAlgorithms: [
      "R",
      "U2'",
      "R'",
      "F",
      "R'",
      "F'",
      "R",
      "U'",
      "R",
      "U'",
      "R'",
    ],
    patternPositions: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "Oll_11",
    name: "OLL-11",
    setupAlgorithms: ["M", "U'", "R", "U2'", "R'", "U'", "R", "U'", "R2'", "r"],
    patternPositions: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "Oll_12",
    name: "OLL-12",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
      "U'",
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
    ],
    patternPositions: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "Oll_13",
    name: "OLL-13",
    setupAlgorithms: ["F'", "U'", "F", "r", "U'", "r'", "U", "r", "U", "r'"],
    patternPositions: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "Oll_14",
    name: "OLL-14",
    setupAlgorithms: ["F", "U", "F'", "R'", "F", "R", "U'", "R'", "F'", "R"],
    patternPositions: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "Oll_15",
    name: "OLL-15",
    setupAlgorithms: ["r'", "U'", "r", "U'", "R'", "U", "R", "r'", "U", "r"],
    patternPositions: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "Oll_16",
    name: "OLL-16",
    setupAlgorithms: ["r", "U", "r'", "U", "R", "U'", "R'", "r", "U'", "r'"],
    patternPositions: [],
    category: OLLCategory.KNIGHT_MOVE_SHAPES,
  },
  {
    id: "Oll_17",
    name: "OLL-17",
    setupAlgorithms: [
      "F",
      "R'",
      "F'",
      "R",
      "U2'",
      "F",
      "R'",
      "F'",
      "R",
      "U'",
      "R",
      "U'",
      "R'",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_18",
    name: "OLL-18",
    setupAlgorithms: [
      "r'",
      "U2'",
      "R",
      "U",
      "R'",
      "U",
      "r2'",
      "U2'",
      "R'",
      "U'",
      "R",
      "U'",
      "r'",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_19",
    name: "OLL-19",
    setupAlgorithms: [
      "F",
      "R'",
      "F'",
      "R",
      "M",
      "U",
      "R",
      "U'",
      "R'",
      "U'",
      "M'",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_20",
    name: "OLL-20",
    setupAlgorithms: [
      "r",
      "U",
      "R'",
      "U'",
      "M2'",
      "U",
      "R",
      "U'",
      "R'",
      "U'",
      "M'",
    ],
    patternPositions: [],
    category: OLLCategory.DOT_CASE,
  },
  {
    id: "Oll_21",
    name: "OLL-21",
    setupAlgorithms: [
      "R",
      "U",
      "R'",
      "U",
      "R",
      "U'",
      "R'",
      "U",
      "R",
      "U2'",
      "R'",
      "y'",
    ],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_22",
    name: "OLL-22",
    setupAlgorithms: ["R'", "U2'", "R2'", "U", "R2'", "U", "R2'", "U2'", "R'"],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_23",
    name: "OLL-23",
    setupAlgorithms: ["R", "U2'", "R", "D", "R'", "U2'", "R", "D'", "R2'"],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_24",
    name: "OLL-24",
    setupAlgorithms: ["F", "R'", "F'", "r", "U", "R", "U'", "r'"],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_25",
    name: "OLL-25",
    setupAlgorithms: ["R'", "F'", "r", "U", "R", "U'", "r'", "F", "y'"],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_26",
    name: "OLL-26",
    setupAlgorithms: ["R", "U", "R'", "U", "R", "U2'", "R'", "y'"],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_27",
    name: "OLL-27",
    setupAlgorithms: ["R", "U2'", "R'", "U'", "R", "U'", "R'"],
    patternPositions: [],
    category: OLLCategory.OCLL,
  },
  {
    id: "Oll_28",
    name: "OLL-28",
    setupAlgorithms: ["R", "U", "R'", "U'", "M'", "U", "R", "U'", "r'"],
    patternPositions: [],
    category: OLLCategory.ALL_CORNERS_ORIENTED,
  },
  {
    id: "Oll_29",
    name: "OLL-29",
    setupAlgorithms: [
      "M",
      "F",
      "R'",
      "F'",
      "R",
      "U",
      "R",
      "U'",
      "R'",
      "U'",
      "M'",
    ],
    patternPositions: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "Oll_30",
    name: "OLL-30",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U2'",
      "R'",
      "U",
      "R",
      "U2'",
      "R'",
      "U'",
      "F'",
      "y2'",
    ],
    patternPositions: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "Oll_31",
    name: "OLL-31",
    setupAlgorithms: ["R'", "F", "R", "U", "R'", "U'", "F'", "U", "R"],
    patternPositions: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "Oll_32",
    name: "OLL-32",
    setupAlgorithms: ["f", "R'", "F'", "R", "U", "R", "U'", "R'", "S'"],
    patternPositions: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "Oll_33",
    name: "OLL-33",
    setupAlgorithms: ["F", "R'", "F'", "R", "U", "R", "U'", "R'"],
    patternPositions: [],
    category: OLLCategory.T_SHAPES,
  },
  {
    id: "Oll_34",
    name: "OLL-34",
    setupAlgorithms: [
      "F",
      "U",
      "R'",
      "U'",
      "R'",
      "F'",
      "R",
      "U",
      "R2'",
      "U'",
      "R'",
      "y2'",
    ],
    patternPositions: [],
    category: OLLCategory.C_SHAPES,
  },
  {
    id: "Oll_35",
    name: "OLL-35",
    setupAlgorithms: ["R", "U2'", "R'", "F", "R'", "F'", "R2'", "U2'", "R'"],
    patternPositions: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "Oll_36",
    name: "OLL-36",
    setupAlgorithms: [
      "F'",
      "L",
      "F",
      "L'",
      "U'",
      "L'",
      "U'",
      "L",
      "U",
      "L'",
      "U",
      "L",
      "y2'",
    ],
    patternPositions: [],
    category: OLLCategory.W_SHAPES,
  },
  {
    id: "Oll_37",
    name: "OLL-37",
    setupAlgorithms: ["F", "R", "U'", "R'", "U", "R", "U", "R'", "F'"],
    patternPositions: [],
    category: OLLCategory.FISH_SHAPES,
  },
  {
    id: "Oll_38",
    name: "OLL-38",
    setupAlgorithms: [
      "F",
      "R'",
      "F'",
      "R",
      "U",
      "R",
      "U",
      "R'",
      "U'",
      "R",
      "U'",
      "R'",
    ],
    patternPositions: [],
    category: OLLCategory.W_SHAPES,
  },
  {
    id: "Oll_39",
    name: "OLL-39",
    setupAlgorithms: ["L", "U", "F'", "U'", "L'", "U", "L", "F", "L'", "y'"],
    patternPositions: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "Oll_40",
    name: "OLL-40",
    setupAlgorithms: ["R'", "U'", "F", "U", "R", "U'", "R'", "F'", "R", "y'"],
    patternPositions: [],
    category: OLLCategory.LIGHTNING_SHAPES,
  },
  {
    id: "Oll_41",
    name: "OLL-41",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
      "R",
      "U2'",
      "R'",
      "U'",
      "R",
      "U'",
      "R'",
      "y2'",
    ],
    patternPositions: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "Oll_42",
    name: "OLL-42",
    setupAlgorithms: [
      "F",
      "U",
      "R",
      "U'",
      "R'",
      "F'",
      "R'",
      "U2'",
      "R",
      "U",
      "R'",
      "U",
      "R",
    ],
    patternPositions: [],
    category: OLLCategory.AWKWARD_SHAPES,
  },
  {
    id: "Oll_43",
    name: "OLL-43",
    setupAlgorithms: ["f'", "U'", "L'", "U", "L", "f"],
    patternPositions: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "Oll_44",
    name: "OLL-44",
    setupAlgorithms: ["f", "U", "R", "U'", "R'", "f'"],
    patternPositions: [],
    category: OLLCategory.P_SHAPES,
  },
  {
    id: "Oll_45",
    name: "OLL-45",
    setupAlgorithms: ["F", "U", "R", "U'", "R'", "F'"],
    patternPositions: [],
    category: OLLCategory.T_SHAPES,
  },
  {
    id: "Oll_46",
    name: "OLL-46",
    setupAlgorithms: ["R'", "U'", "F", "R'", "F'", "R", "U", "R"],
    patternPositions: [],
    category: OLLCategory.C_SHAPES,
  },
  {
    id: "Oll_47",
    name: "OLL-47",
    setupAlgorithms: ["F'", "U'", "L'", "U", "L", "U'", "L'", "U", "L", "F"],
    patternPositions: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "Oll_48",
    name: "OLL-48",
    setupAlgorithms: ["F", "U", "R", "U'", "R'", "U", "R", "U'", "R'", "F'"],
    patternPositions: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "Oll_49",
    name: "OLL-49",
    setupAlgorithms: [
      "r'",
      "U",
      "r2'",
      "U'",
      "r2'",
      "U'",
      "r2'",
      "U",
      "r'",
      "y2'",
    ],
    patternPositions: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "Oll_50",
    name: "OLL-50",
    setupAlgorithms: ["r", "U'", "r2'", "U", "r2'", "U", "r2'", "U'", "r"],
    patternPositions: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "Oll_51",
    name: "OLL-51",
    setupAlgorithms: ["f", "U", "R", "U'", "R'", "U", "R", "U'", "R'", "f'"],
    patternPositions: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "Oll_52",
    name: "OLL-52",
    setupAlgorithms: ["F", "R", "U", "R'", "d", "R'", "U'", "R", "U'", "R'"],
    patternPositions: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "Oll_53",
    name: "OLL-53",
    setupAlgorithms: [
      "r'",
      "U2'",
      "R",
      "U",
      "R'",
      "U'",
      "R",
      "U",
      "R'",
      "U",
      "r",
    ],
    patternPositions: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "Oll_54",
    name: "OLL-54",
    setupAlgorithms: [
      "r",
      "U2'",
      "R'",
      "U'",
      "R",
      "U",
      "R'",
      "U'",
      "R",
      "U'",
      "r'",
    ],
    patternPositions: [],
    category: OLLCategory.L_SHAPES,
  },
  {
    id: "Oll_55",
    name: "OLL-55",
    setupAlgorithms: [
      "F",
      "R'",
      "F'",
      "U2'",
      "R",
      "U",
      "R'",
      "U",
      "R2'",
      "U2'",
      "R'",
    ],
    patternPositions: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "Oll_56",
    name: "OLL-56",
    setupAlgorithms: [
      "r",
      "U",
      "r'",
      "R",
      "U",
      "R'",
      "U'",
      "R",
      "U",
      "R'",
      "U'",
      "r",
      "U'",
      "r'",
    ],
    patternPositions: [],
    category: OLLCategory.LINE_SHAPES,
  },
  {
    id: "Oll_57",
    name: "OLL-57",
    setupAlgorithms: ["r", "U", "R'", "U'", "M", "U", "R", "U'", "R'"],
    patternPositions: [],
    category: OLLCategory.ALL_CORNERS_ORIENTED,
  },
];

export default definitions;
