import type { PLLDefinition } from "@/types/cube/333";
import { PLLCategory } from "@/enums/cube/333";

export type { PLLDefinition, PLLCaseId } from "@/types/cube/333";

export const definitions: PLLDefinition[] = [
  {
    id: "Aa",
    name: "PLL Aa",
    setupAlgorithm: "x R2' D2' R U R' D2' R U' R x'",
    pattern: {
      "S-TL": "R",
      "S-TC": "B",
      "S-TR": "R",
      "S-LT": "B",
      "S-LC": "L",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "B",
      "S-RT": "F",
      "S-RC": "R",
      "S-RB": "L",
    },
    algorithms: [
      "R' F R' B2 R F' R' B2 R2",
      "x' R' D R' U2 R D' R' U2 R2 x",
      "x R' U R' D2 R U' R' D2 R2 x'",
      "l' U R' D2 R U' R' D2 R2 x'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Ab",
    name: "PLL Ab",
    setupAlgorithm: "x R' U R' D2' R U' R' D2' R2' x'",
    pattern: {
      "S-TL": "F",
      "S-TC": "B",
      "S-TR": "L",
      "S-LT": "R",
      "S-LC": "L",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "R",
      "S-RT": "B",
      "S-RC": "R",
      "S-RB": "B",
    },
    algorithms: [
      "R B' R F2 R' B R F2 R2",
      "x R D' R U2 R' D R U2 R2 x'",
      "x' R U' R D2 R' U R D2 R2 x",
      "y' x R2 D2 R U R' D2 R U' R x'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "E",
    name: "PLL E",
    setupAlgorithm: "x' D R U R' D' R U' R' D R U' R' D' R U R' x y'",
    pattern: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "B",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "L",
      "S-BR": "B",
      "S-RT": "R",
      "S-RC": "F",
      "S-RB": "L",
    },
    algorithms: [
      "y x' R U' R' D R U R' D' R U R' D R U' R' D' x",
      "R2 U R' U' y R U R' U' R U R' U' R U R' y' R U' R2",
      "z U2' R2' F R U R' U' R U R' U' R U R' U' F' R2 U2'",
      "y x' R U' R' D R U R' u2 R' U R D R' U' R x",
    ],
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "F",
    name: "PLL F",
    setupAlgorithm: "R' U' R U' R' U R U R2' F' R U R U' R' F U R y'",
    pattern: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "F",
      "S-LB": "B",
      "S-BL": "L",
      "S-BC": "L",
      "S-BR": "L",
      "S-RT": "R",
      "S-RC": "B",
      "S-RB": "F",
    },
    algorithms: [
      "R' U R U' R2 F' U' F U R F R' F' R2 U'",
      "R' U R U' R2 y' R' U' R U y x R U R' U' R2 x'",
      "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
      "y' L U F L' U' L U L F' L2 U L U L' U' L U' L'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Ga",
    name: "PLL Ga",
    setupAlgorithm: "R' U' R D' U R2' U R' U R U' R U' R2' D",
    pattern: {
      "S-TL": "B",
      "S-TC": "F",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "B",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "R",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "L",
      "S-RB": "B",
    },
    algorithms: [
      "R2 U R' U R' U' R U' R2 D U' R' U R D'",
      "y R2' u R' U R' U' R u' R2 y' R' U R",
      "y R2 U R' U R' U' R U' R2 D U' R' U R D'",
      "y2 F2' D R' U R' U' R D' F2 L' U L",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Gb",
    name: "PLL Gb",
    setupAlgorithm: "R2' U R' U R' U' R U' R2' D U' R' U R D'",
    pattern: {
      "S-TL": "B",
      "S-TC": "L",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "B",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "F",
      "S-RB": "B",
    },
    algorithms: [
      "R' U' R y R2 u R' U R U' R u' R2",
      "R' U' R U D' R2 U R' U R U' R U' R2 D",
      "y F' U' F R2 u R' U R U' R u' R2",
      "R' d' F R2 u R' U R U' R u' R2",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Gc",
    name: "PLL Gc",
    setupAlgorithm: "D' R U R' U' D R2' U' R U' R' U R' U R2'",
    pattern: {
      "S-TL": "B",
      "S-TC": "R",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "F",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "B",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "L",
      "S-RB": "B",
    },
    algorithms: [
      "y R2' u' R U' R U R' u R2 y R U' R'",
      "y R2' u' R U' R U R' u R2 B U' B'",
      "y R2' U' R U' R U R' U R2 D' U R U' R' D",
      "y R2' D' F U' F U F' D R2 B U' B'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Gd",
    name: "PLL Gd",
    setupAlgorithm: "R2' U' R U' R U R' U R2' D' U R U' R' D",
    pattern: {
      "S-TL": "B",
      "S-TC": "F",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "L",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "B",
      "S-RB": "B",
    },
    algorithms: [
      "y2 R U R' y' R2 u' R U' R' U R' u R2",
      "y2 R U R' F2 D' L U' L' U L' D F2",
      "y2 L U2 L' U F' L' U' L U L F U L' U' L' U L",
      "y2 l2 U' L2 U' F2 L' U' R U2 L' U l x'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "H",
    name: "PLL H",
    setupAlgorithm: "M2' U' M2' U2' M2' U' M2'",
    pattern: {
      "S-TL": "B",
      "S-TC": "F",
      "S-TR": "B",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "B",
      "S-BR": "F",
      "S-RT": "R",
      "S-RC": "L",
      "S-RB": "R",
    },
    algorithms: [
      "M2 U M2 U2 M2 U M2",
      "M2 U' M2 U2 M2 U' M2",
      "R2 U2 R U2 R2 U2 R2 U2 R U2 R2",
      "M2' U' M2' U2' M2' U' M2'",
    ],
    category: PLLCategory.EPLL,
  },
  {
    id: "Ja",
    name: "PLL Ja",
    setupAlgorithm: "L' R' U2' R U R' U2' L U' R y'",
    pattern: {
      "S-TL": "R",
      "S-TC": "F",
      "S-TR": "F",
      "S-LT": "B",
      "S-LC": "B",
      "S-LB": "F",
      "S-BL": "R",
      "S-BC": "R",
      "S-BR": "B",
      "S-RT": "L",
      "S-RC": "L",
      "S-RB": "L",
    },
    algorithms: [
      "B' U F' U2 B U' B' U2 F B U'",
      "y R' U L' U2 R U' R' U2 R L",
      "y' L' U R' U2 L U' L' U2 R L",
      "y' L' U R' z R2 U R' U' R2 U D z'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Jb",
    name: "PLL Jb",
    setupAlgorithm: "R U R2' F' R U R U' R' F R U' R'",
    pattern: {
      "S-TL": "R",
      "S-TC": "R",
      "S-TR": "F",
      "S-LT": "B",
      "S-LC": "B",
      "S-LB": "B",
      "S-BL": "L",
      "S-BC": "F",
      "S-BR": "F",
      "S-RT": "L",
      "S-RC": "L",
      "S-RB": "R",
    },
    algorithms: [
      "R U R' F' R U R' U' R' F R2 U' R' U'",
      "R U2 R' U' R U2 L' U R' U' r x",
      "R U2 R' U' R U2 L' U R' U' L",
      "L' U R U' L U2' R' U R U2' R'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Na",
    name: "PLL Na",
    setupAlgorithm: "R U R' U2' R U R2' F' R U R U' R' F R U' R' U' R U' R'",
    pattern: {
      "S-TL": "B",
      "S-TC": "B",
      "S-TR": "F",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "R",
      "S-BL": "B",
      "S-BC": "F",
      "S-BR": "F",
      "S-RT": "L",
      "S-RC": "L",
      "S-RB": "R",
    },
    algorithms: [
      "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
      "L U' R U2 L' U R' L U' R U2 L' U R'",
      "z U R' D R2 U' R D' U R' D R2 U' R D' z'",
      "r' D r U2 r' D r U2 r' D r U2 r' D r U2 r' D r",
    ],
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Nb",
    name: "PLL Nb",
    setupAlgorithm: "F r' F' r U r U' r2' D' F r U r' F' D r",
    pattern: {
      "S-TL": "F",
      "S-TC": "B",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "B",
      "S-RT": "R",
      "S-RC": "L",
      "S-RB": "L",
    },
    algorithms: [
      "R' U L' U2 R U' L R' U L' U2 R U' L",
      "R' U R U' R' F' U' F R U R' F R' F' R U' R",
      "z D' R U' R2 D R' U D' R U' R2 D R' U z'",
      "z U' R D' R2 U R' D U' R D' R2 U R' D z'",
    ],
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Ra",
    name: "PLL Ra",
    setupAlgorithm: "R U2' R D R' U R D' R' U' R' U R U R' y'",
    pattern: {
      "S-TL": "L",
      "S-TC": "F",
      "S-TR": "R",
      "S-LT": "F",
      "S-LC": "B",
      "S-LB": "R",
      "S-BL": "B",
      "S-BC": "R",
      "S-BR": "B",
      "S-RT": "F",
      "S-RC": "L",
      "S-RB": "L",
    },
    algorithms: [
      "y2 L U2 L' U2 L F' L' U' L U L F L2",
      "y' R U R' F' R U2 R' U2 R' F R U R U2 R'",
      "y' R U' R' U' R U R D R' U' R D' R' U2 R'",
      "R U2 R' U2 R B' R' U' R U R B R2 U",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Rb",
    name: "PLL Rb",
    setupAlgorithm: "R' U R U R' U' R' D' R U R' D R U2' R",
    pattern: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "B",
      "S-LB": "B",
      "S-BL": "L",
      "S-BC": "F",
      "S-BR": "L",
      "S-RT": "R",
      "S-RC": "L",
      "S-RB": "F",
    },
    algorithms: [
      "R' U2 R U2 R' F R U R' U' R' F' R2",
      "R' U2 R' D' R U' R' D R U R U' R' U' R",
      "y R2 F R U R U' R' F' R U2 R' U2 R",
      "y' R U2' R' U2 R' F R2 U' R' U' R U R' F' R U R' U R U2 R'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "T",
    name: "PLL T",
    setupAlgorithm: "F R' F' R U R U R2' F' R U R U' R'",
    pattern: {
      "S-TL": "B",
      "S-TC": "B",
      "S-TR": "R",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "R",
      "S-RT": "F",
      "S-RC": "L",
      "S-RB": "B",
    },
    algorithms: [
      "R U R' U' R' F R2 U' R' U' R U R' F'",
      "R U R' U' R' F R2 U' R' U F' L' U L",
      "R2 U R2 U' R2 U' D R2 U' R2 U R2 D'",
      "y F2 D R2 U' R2 F2 D' L2 U L2 U'",
    ],
    category: PLLCategory.ADJ_SWAP,
  },
  {
    id: "Ua",
    name: "PLL Ua",
    setupAlgorithm: "M2' U' M' U2' M U' M2'",
    pattern: {
      "S-TL": "B",
      "S-TC": "L",
      "S-TR": "B",
      "S-LT": "L",
      "S-LC": "R",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "F",
      "S-RT": "R",
      "S-RC": "B",
      "S-RB": "R",
    },
    algorithms: [
      "R2 U' R' U' R U R U R U' R",
      "y2 R U' R U R U R U' R' U' R2",
      "M2 U M' U2 M U M2",
      "y2 M2 U M U2 M' U M2",
    ],
    category: PLLCategory.EPLL,
  },
  {
    id: "Ub",
    name: "PLL Ub",
    setupAlgorithm: "M2' U M' U2' M U M2'",
    pattern: {
      "S-TL": "B",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "L",
      "S-LC": "B",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "F",
      "S-RT": "R",
      "S-RC": "L",
      "S-RB": "R",
    },
    algorithms: [
      "R' U R' U' R' U' R' U R U R2",
      "y2 M2 U' M U2 M' U' M2",
      "y2 R2' U R U R' U' R' U' R' U R'",
      "M2 U' M' U2 M U' M2",
    ],
    category: PLLCategory.EPLL,
  },
  {
    id: "V",
    name: "PLL V",
    setupAlgorithm: "D2' R' U R D' R2' U' R' U R' U R' D' R U2' R'",
    pattern: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "L",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "B",
      "S-RT": "R",
      "S-RC": "B",
      "S-RB": "L",
    },
    algorithms: [
      "R' U R' d' R' F' R2 U' R' U R' F R F",
      "R' U R' U' y R' F' R2 U' R' U R' F R F",
      "z D' R2 D R2' U R' D' R U' R U R' D R U'",
      "R U2 R' D R U' R U' R U R2 D R' U' R D2",
    ],
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Y",
    name: "PLL Y",
    setupAlgorithm: "F R' F' R U R U' R' F R U' R' U R U R' F'",
    pattern: {
      "S-TL": "F",
      "S-TC": "L",
      "S-TR": "B",
      "S-LT": "R",
      "S-LC": "B",
      "S-LB": "L",
      "S-BL": "F",
      "S-BC": "F",
      "S-BR": "B",
      "S-RT": "R",
      "S-RC": "R",
      "S-RB": "L",
    },
    algorithms: [
      "F R U' R' U' R U R' F' R U R' U' R' F R F'",
      "F R' F R2 U' R' U' R U R' F' R U R' U' F'",
      "R2 U' R2 U' R2 U y' R U R' B2 R U' R'",
      "R2 U' R' U R U' y' x' L' U' R U' R' U' L U",
    ],
    category: PLLCategory.OPP_SWAP,
  },
  {
    id: "Z",
    name: "PLL Z",
    setupAlgorithm: "M U2' M2' U2' M U' M2' U' M2'",
    pattern: {
      "S-TL": "F",
      "S-TC": "R",
      "S-TR": "F",
      "S-LT": "R",
      "S-LC": "F",
      "S-LB": "R",
      "S-BL": "B",
      "S-BC": "L",
      "S-BR": "B",
      "S-RT": "L",
      "S-RC": "B",
      "S-RB": "L",
    },
    algorithms: [
      "M2 U M2 U M' U2 M2 U2 M'",
      "y M2' U' M2' U' M' U2' M2' U2' M'",
      "M' U' M2' U' M2' U' M' U2' M2'",
      "R' U' R2 U R U R' U' R U R U' R U' R'",
    ],
    category: PLLCategory.EPLL,
  },
];
